module 2 : Desktop view with 768px(including media queries)
arnold-O/portfolio_project_microverse pull request #6
Opened 2023-01-20 18:40 UTC by arnold-O

- Navbar Section( styling it to a toolbar)
- Headline Section
- Portfolio Section
- About Section
- Contact Section
- Footer Section

2023-01-20 20:52 UTC, laiifuu requested changes
## Hi @arnold-O :wave: 

Good job so far on the desktop version of this portfolio website :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!
![so-close-jim-halpert](https://user-images.githubusercontent.com/93520178/213802711-b57ca143-07c8-4d64-90aa-7ed5653fb301.gif)

## Highlights
- [x] Good use of the media queries :heavy_check_mark: 
- [x] Both Flexbox and Grid used for the layout :heavy_check_mark:  

## Required Changes ♻️
- [ ] Nice work on the README.MD file, it's looking professional :+1:. I suggest you remove the  section description for the Key features and the Authors sections to make it even better. 

![Screenshot from 2023-01-20 21-44-05](https://user-images.githubusercontent.com/93520178/213801901-d1f5c760-5d66-4b2b-9eb5-265955d4f82c.png)
![Screenshot from 2023-01-20 21-44-13](https://user-images.githubusercontent.com/93520178/213801969-3d171448-0045-4e2a-bbe3-93ffaa19ee6c.png)


_Please check the comments under the review :point_down:_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and :computer: Happy coding :computer: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 20:52 UTC, laiifuu commented on index.html
>      <section class="project-section  margin-md-sm">
This section has more space separating it from the hero section according to the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9&t=ZDuO8dQqVjKz2a5j-0). Kindly stick to the design by adding margin or padding to its top side. 

### The template: 

![Screenshot from 2023-01-20 20-58-25](https://user-images.githubusercontent.com/93520178/213794290-207bb5fc-ab60-4621-b54e-5bd3d664a61c.png)
### Your design:

![Screenshot from 2023-01-20 20-58-42](https://user-images.githubusercontent.com/93520178/213794370-f0b21b18-392e-42e2-902e-cfca2a2ddfa9.png)

2023-01-20 20:52 UTC, laiifuu commented on style.css
> +  }
The content of this div look bigger in the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9&t=ZDuO8dQqVjKz2a5j-0). Kindly stick to the design by adjusting its size.

2023-01-20 20:52 UTC, laiifuu commented on style.css
> +  }
The about section should have more space separating it from the projects section as well as more spacing on its left and right side according to the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9&t=ZDuO8dQqVjKz2a5j-0).

2023-01-20 20:52 UTC, laiifuu commented on style.css
> +  }
For this div, The title 'About' and the description text should be separated with more space. After removing the margin-top on the `Get my cv` button, you can achieve this by making the div's display set to flex with a flex-direction set to column and a gap of 30px. Something like this: 
` .about-section-description { display: flex;
    flex-direction: column;
    gap: 30px;
    padding: 2rem;
    order: 2;
}`

2023-01-20 20:52 UTC, laiifuu commented on index.html
> +                <p>Get started</p>
I suggest you use a heading tag (h2) here instead of a paragraph tag to reflect that this is a heading for this section. 
It should also have a font size of 110px for it to look like what's in the Figma template.

2023-01-20 20:52 UTC, laiifuu commented on style.css
> +  }
Kindly stick to the Figma template by adjusting the alignment of the Get Started section content. 
### The template: 
![Screenshot from 2023-01-20 21-33-13](https://user-images.githubusercontent.com/93520178/213800951-f636d4c0-7e24-483b-8f25-47f421665db1.png)
### Your design

![Screenshot from 2023-01-20 21-32-26](https://user-images.githubusercontent.com/93520178/213801075-d1a8cb50-a039-48b5-939a-73f9c73c100d.png)

2023-01-21 10:51 UTC, arnold-O commented
A 768px media screen to fit into the design of **Figma template 5** will result in a squash design, hence I had to design for 1000px and above after  **@laiifuu** came back,  in other to accommodate all dimensions as much as possible.
please **reviewer** take note.

2023-01-21 14:01 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @arnold-O, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://user-images.githubusercontent.com/20554583/192241479-b6304cb0-f256-4c64-a258-4f5a40a1e960.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 15:33 UTC, ha-manel approved these changes
# STATUS: APPROVED ✅

## Hi @arnold-O 👋

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉**

<img src="https://media3.giphy.com/media/l4JySAWfMaY7w88sU/giphy.gif"/>

## Highlights:
* Well-written PR description ✔️ 
* All tests passed ✔️ 

## Optional suggestions:

- [ ] Please consider using best practices when you write commit messages, they should be capitalized sentences in the imperative form, example: "Add linters" instead of "added linters" or "linters are added" ... etc 👍 
- [ ] Kindly add the MIT file to your project because the link in your README file is broken 😓 


------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 15:46 UTC, merged